spring:
  application:
    name: ai-demo
  ai:
    chat:
      client:
        enabled: false
    ollama:
      chat:
        options:
          model: llama3.2:1b
    openai:
      api-key: ${OPENAI_API_KEY:DummyKey}
logging:
  level:
    root: INFO
    "[org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor]": DEBUG
