server:
  address: 0.0.0.0
  port: 8080
spring:
  application:
    name: springai
  ai:
    model:
      chat: ollama
    ollama:
      chat:
        options:
          model: llama3.2:1b
     
    # openai: 
    #   api-key: ${OPENAI_API_KEY}
      
logging:
  pattern:
    console: "%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %highlight(%-5level) %red([%thread]) %cyan(%logger{36}) %yellow([%X{traceId:-} %X{spanId:-}]) - %msg%n%ex{full}"